# Generated by Django 2.2.4 on 2020-11-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
